-- Use the NTILE functionality to divide the accounts into two levels in terms of the amount of gloss_qty for their orders.Your resulting table should have the account_id,
-- the occurred_at time for each order,
-- the total amount of gloss_qty paper purchased,
-- and one of two levels in a gloss_half column.